import { VideoGraphResponse } from './types';

export const DEMO_3B1B_GRAPH: VideoGraphResponse = {
  video_id: 'wjZofJX0v4U',
  video_title: 'Attention in transformers, visually explained | Chapter 5, Deep Learning',
  channel: '3Blue1Brown',
  duration_formatted: '23:40',
  executive_takeaway: 'Transformers replace recurrence with parallel self-attention, dynamically routing information through query-key affinities while trading off quadratic sequence scaling.',
  nodes: [
    {
      id: 'self-attention',
      label: 'Self-Attention',
      category: 'Core Concept',
      summary: 'Dynamic weighting mechanism that relates different token positions in a sequence.',
      description: 'Allows each token to incorporate context from all other tokens in parallel using query and key affinities. Replaces sequential recurrence with direct matrix multiplication.',
      key_points: [
        'Computes relevance weights via scaled dot products',
        'Enables bidirectional context across full sequence',
        'Operates in parallel across all positions simultaneously',
      ],
      timestamp_seconds: 30,
      timestamp_formatted: '00:30',
      val: 12,
    },
    {
      id: 'query-key-value',
      label: 'Query, Key & Value Vectors',
      category: 'Core Concept',
      summary: 'Triad of projection vectors derived from token embeddings.',
      description: 'Each token generates queries to request information, keys to advertise relevance, and values to deliver content. Relevance scores dynamically weight incoming value vectors.',
      key_points: [
        'Query seeks matching context from surrounding tokens',
        'Key acts as addressable feature identifier',
        'Value carries actual semantic payload',
      ],
      timestamp_seconds: 240,
      timestamp_formatted: '04:00',
      val: 11,
    },
    {
      id: 'scaled-dot-product',
      label: 'Scaled Dot-Product',
      category: 'Method',
      summary: 'Matrix operation computing token-to-token similarity scores.',
      description: 'Calculates inner products between queries and keys divided by the square root of dimension size. Softmax then converts raw scores into probability distributions.',
      key_points: [
        'Division by sqrt(d_k) prevents vanishing gradients',
        'Softmax yields normalized attention weights',
        'Multiplication by values produces context representation',
      ],
      timestamp_seconds: 320,
      timestamp_formatted: '05:20',
      val: 10,
    },
    {
      id: 'multi-head-attention',
      label: 'Multi-Head Attention',
      category: 'Method',
      summary: 'Parallel attention heads capturing distinct semantic relationships simultaneously.',
      description: 'Splits queries, keys, and values into multiple subspace projections trained independently. Allows the model to simultaneously attend to syntax, coreference, and tone.',
      key_points: [
        'H independent linear projection heads',
        'Captures diverse linguistic relationships in parallel',
        'Outputs concatenated and linearly projected',
      ],
      timestamp_seconds: 520,
      timestamp_formatted: '08:40',
      val: 11,
    },
    {
      id: 'word-embeddings',
      label: 'Word Embeddings',
      category: 'Core Concept',
      summary: 'High-dimensional continuous vector representations of discrete tokens.',
      description: 'Maps discrete vocabulary indices into continuous geometric space where proximity denotes semantic similarity. Forms the base input layer for the transformer network.',
      key_points: [
        'Maps vocabulary tokens into continuous vector space',
        'Geometric distance reflects semantic similarity',
        'Serves as initial input to transformer blocks',
      ],
      timestamp_seconds: 90,
      timestamp_formatted: '01:30',
      val: 9,
    },
    {
      id: 'positional-encoding',
      label: 'Positional Encoding',
      category: 'Core Concept',
      summary: 'Sinusoidal or learned vectors injected into embeddings to preserve token order.',
      description: 'Adds frequency wave patterns directly to input embeddings before attention. Supplies essential word order information that permutation-invariant attention ignores.',
      key_points: [
        'Adds sinusoidal wave patterns across dimensions',
        'Provides sequence ordering without recurrence',
        'Prevents bag-of-words order blindness',
      ],
      timestamp_seconds: 160,
      timestamp_formatted: '02:40',
      val: 9,
    },
    {
      id: 'feed-forward-network',
      label: 'Feed-Forward Network',
      category: 'Method',
      summary: 'Position-wise two-layer dense network operating on each token independently.',
      description: 'Applies identical non-linear transformations to each position after multi-head attention. Functions as associative key-value memory storing factual knowledge.',
      key_points: [
        'Applies position-wise without inter-token mixing',
        'Expands hidden dimension fourfold before contracting',
        'Stores cross-token associative facts',
      ],
      timestamp_seconds: 870,
      timestamp_formatted: '14:30',
      val: 9,
    },
    {
      id: 'residual-connections',
      label: 'Residual Connections',
      category: 'Tool',
      summary: 'Additive skip connections bypassing layers to maintain gradient flow.',
      description: 'Adds sub-layer inputs directly to their outputs prior to normalization. Prevents vanishing gradients across deep stacks and preserves clean identity mapping.',
      key_points: [
        'Provides direct gradient superhighway during training',
        'Enables stacking dozens of attention layers',
        'Prevents degradation of earlier layer features',
      ],
      timestamp_seconds: 640,
      timestamp_formatted: '10:40',
      val: 8,
    },
    {
      id: 'layer-normalization',
      label: 'Layer Normalization',
      category: 'Tool',
      summary: 'Per-token activation stabilization applied across feature dimensions.',
      description: 'Normalizes activations across the hidden channels of each token independently. Stabilizes internal dynamics and prevents activation values from exploding.',
      key_points: [
        'Normalizes across hidden channel dimensions',
        'Stabilizes forward activations and backward gradients',
        'Enables faster and more consistent convergence',
      ],
      timestamp_seconds: 750,
      timestamp_formatted: '12:30',
      val: 8,
    },
    {
      id: 'quadratic-complexity',
      label: 'Quadratic Bottleneck',
      category: 'Warning',
      summary: 'Compute and memory scaling bottleneck of full dense self-attention.',
      description: 'Comparing every token to every other token scales compute and VRAM memory by O(N^2). Restricts context window size on hardware unless sparse attention is used.',
      key_points: [
        'O(N^2) memory and compute footprint',
        'Limits context length on standard GPU hardware',
        'Motivates FlashAttention and sparse architectures',
      ],
      timestamp_seconds: 1020,
      timestamp_formatted: '17:00',
      val: 10,
    },
  ],
  edges: [
    { source: 'word-embeddings', target: 'positional-encoding', relationship: 'combines with', strength: 2 },
    { source: 'positional-encoding', target: 'self-attention', relationship: 'inputs into', strength: 3 },
    { source: 'self-attention', target: 'query-key-value', relationship: 'projects into', strength: 3 },
    { source: 'query-key-value', target: 'scaled-dot-product', relationship: 'computes affinity via', strength: 3 },
    { source: 'scaled-dot-product', target: 'multi-head-attention', relationship: 'parallelized as', strength: 3 },
    { source: 'multi-head-attention', target: 'residual-connections', relationship: 'bypassed by', strength: 2 },
    { source: 'residual-connections', target: 'layer-normalization', relationship: 'stabilized by', strength: 2 },
    { source: 'layer-normalization', target: 'feed-forward-network', relationship: 'feeds into', strength: 2 },
    { source: 'self-attention', target: 'quadratic-complexity', relationship: 'suffers from', strength: 3 },
  ],
};

export const DEMO_KARPATHY_GRAPH: VideoGraphResponse = {
  video_id: 'kCc8FmEb1nY',
  video_title: "Let's build GPT: from scratch, in code, spelled out.",
  channel: 'Andrej Karpathy',
  duration_formatted: '01:56:00',
  executive_takeaway: 'A comprehensive build of GPT from scratch, starting with bigram baselines and assembling masked self-attention, residual streams, and autoregressive generation.',
  nodes: [
    {
      id: 'bigram-model',
      label: 'Bigram Language Model',
      category: 'Core Concept',
      summary: 'Baseline probabilistic model predicting next tokens from the immediate previous character.',
      description: 'Establishes the minimal baseline architecture before introducing attention blocks. Relies on lookup tables without multi-token contextual history.',
      key_points: [
        'Simplest next-token prediction baseline',
        'Lookup table mapping tokens to next probabilities',
        'High loss baseline without context memory',
      ],
      timestamp_seconds: 120,
      timestamp_formatted: '02:00',
      val: 8,
    },
    {
      id: 'tokenization',
      label: 'Tokenization & Vocab',
      category: 'Method',
      summary: 'Process converting character sequences into discrete integer token IDs.',
      description: 'Transforms strings into integer indices according to a fixed character or BPE vocabulary. Establishes the coordinate system used by tensor embeddings.',
      key_points: [
        'Maps characters or subwords to vocabulary IDs',
        'Balances sequence length against vocabulary size',
        'Provides encode and decode tensor mappings',
      ],
      timestamp_seconds: 300,
      timestamp_formatted: '05:00',
      val: 9,
    },
    {
      id: 'self-attention-block',
      label: 'Self-Attention Block',
      category: 'Core Concept',
      summary: 'Dynamic inter-token communication mechanism computing pairwise affinities.',
      description: 'Allows tokens to query their predecessors and aggregate relevant contextual data. Enables data-dependent communication without fixed recurrence steps.',
      key_points: [
        'Data-dependent affinity matrix calculation',
        'Replaces convolutional and recurrent links',
        'Core computation of generative language models',
      ],
      timestamp_seconds: 900,
      timestamp_formatted: '15:00',
      val: 12,
    },
    {
      id: 'causal-masking',
      label: 'Causal Masking (Tril)',
      category: 'Method',
      summary: 'Lower-triangular boolean mask preventing future token peek-ahead.',
      description: 'Replaces upper-triangular affinity values with negative infinity before softmax. Guarantees autoregressive correctness during generative training.',
      key_points: [
        'Zeros out future token attention weights',
        'Enforces strict left-to-right causal context',
        'Implemented efficiently using torch.tril',
      ],
      timestamp_seconds: 1400,
      timestamp_formatted: '23:20',
      val: 10,
    },
    {
      id: 'multi-head-attention',
      label: 'Multi-Head Attention',
      category: 'Method',
      summary: 'Parallel attention heads capturing diverse relationship subspaces simultaneously.',
      description: 'Runs multiple independent attention heads over subdivided embedding dimensions. Concatenates outputs and applies a linear projection back to model width.',
      key_points: [
        'Splits embeddings across multiple parallel heads',
        'Learns diverse relational patterns simultaneously',
        'Concatenates and linearly projects outputs',
      ],
      timestamp_seconds: 1600,
      timestamp_formatted: '26:40',
      val: 11,
    },
    {
      id: 'residual-connections',
      label: 'Residual Connections',
      category: 'Tool',
      summary: 'Identity skip connections providing uninterrupted gradient paths.',
      description: 'Channels input activations around attention and MLP blocks directly into the sum. Prevents vanishing gradients across deep multi-layer transformer stacks.',
      key_points: [
        'Acts as direct gradient highway',
        'Enables optimization of deep transformer blocks',
        'Formulated as x = x + block(x)',
      ],
      timestamp_seconds: 1900,
      timestamp_formatted: '31:40',
      val: 9,
    },
    {
      id: 'pre-ln-architecture',
      label: 'Pre-LN Architecture',
      category: 'Method',
      summary: 'LayerNorm placement prior to sub-layer transformations.',
      description: 'Normalizes activations immediately before entering attention and feed-forward sub-blocks. Improves optimization stability over earlier Post-LN designs.',
      key_points: [
        'Applies normalization before sub-layer operations',
        'Modern GPT standard for training stability',
        'Leaves residual highway clean and unscaled',
      ],
      timestamp_seconds: 2400,
      timestamp_formatted: '40:00',
      val: 9,
    },
    {
      id: 'cross-entropy-loss',
      label: 'Cross-Entropy Loss',
      category: 'Method',
      summary: 'Negative log likelihood measuring probability assigned to true target tokens.',
      description: 'Evaluates output logits against ground truth target IDs shifted by one position. Drives backpropagation updates across all neural weights.',
      key_points: [
        'Measures next-token prediction error',
        'Combines log-softmax with negative log likelihood',
        'Drives weight gradient descent updates',
      ],
      timestamp_seconds: 3100,
      timestamp_formatted: '51:40',
      val: 8,
    },
    {
      id: 'adamw-optimizer',
      label: 'AdamW Optimizer',
      category: 'Tool',
      summary: 'Adaptive gradient optimizer decoupling weight decay from momentum.',
      description: 'Maintains exponential moving averages of gradients and squared gradients for each parameter. Standard optimizer choice for fast, stable transformer training.',
      key_points: [
        'Decouples L2 regularization from gradient momentum',
        'Per-parameter adaptive learning rates',
        'Crucial for stable neural network training',
      ],
      timestamp_seconds: 3800,
      timestamp_formatted: '01:03:20',
      val: 8,
    },
    {
      id: 'autoregressive-sampling',
      label: 'Autoregressive Sampling',
      category: 'Method',
      summary: 'Sequential generation loop appending predicted tokens step by step.',
      description: 'Applies temperature scaling and softmax to logits before sampling new tokens. Appends sampled tokens to the context window to iteratively generate text.',
      key_points: [
        'Sequentially appends newly predicted tokens',
        'Controls randomness using temperature scaling',
        'Generates coherent prose token by token',
      ],
      timestamp_seconds: 4600,
      timestamp_formatted: '01:16:40',
      val: 10,
    },
  ],
  edges: [
    { source: 'bigram-model', target: 'tokenization', relationship: 'processes', strength: 2 },
    { source: 'tokenization', target: 'self-attention-block', relationship: 'feeds', strength: 2 },
    { source: 'self-attention-block', target: 'causal-masking', relationship: 'constrained by', strength: 3 },
    { source: 'causal-masking', target: 'multi-head-attention', relationship: 'parallelized in', strength: 3 },
    { source: 'multi-head-attention', target: 'residual-connections', relationship: 'bypassed via', strength: 2 },
    { source: 'residual-connections', target: 'pre-ln-architecture', relationship: 'stabilized by', strength: 2 },
    { source: 'pre-ln-architecture', target: 'cross-entropy-loss', relationship: 'evaluated with', strength: 2 },
    { source: 'cross-entropy-loss', target: 'adamw-optimizer', relationship: 'guides updates in', strength: 3 },
    { source: 'adamw-optimizer', target: 'autoregressive-sampling', relationship: 'powers', strength: 2 },
  ],
};

export function getDemoGraphByUrl(url: string): VideoGraphResponse | null {
  if (url.includes('wjZofJX0v4U')) {
    return DEMO_3B1B_GRAPH;
  }
  if (url.includes('kCc8FmEb1nY')) {
    return DEMO_KARPATHY_GRAPH;
  }
  return null;
}
